arm_controllers:
    base_yaw_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: shoulder_yaw
        joint_speed: 1.17
        motor:
            id: 1
            init: 512
            min: 0
            max: 1023

    torso_pitch_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller_dual_motor
            type: JointPositionControllerDual
        joint_name: shoulder_pitch
        joint_speed: 1.17
        motor_master:
            id: 2
            init: 512
            min: 215
            max: 815
        motor_slave:
            id: 3
            calibration_offset: -pi/2.0

    elbow_pitch_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller_dual_motor
            type: JointPositionControllerDual
        joint_name: elbow_pitch
        joint_speed: 1.17
        motor_master:
            id: 4
            init: 512
            min: 200
            max: 800
        motor_slave:
            id: 5
            calibration_offset: pi/2.0

    wrist_pitch_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: wrist_pitch
        joint_speed: 1.17
        reverse: true
        motor:
            id: 6
            init: 512
            min: 256
            max: 768

    wrist_yaw_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: wrist_yaw
        joint_speed: 1.17
        motor:
            id: 7
            init: 512
            min: 256
            max: 768

    gripper_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: gripper
        joint_speed: 1.17
        motor:
            id: 8
            init: 512
            min: 0
            max: 600