arm_controllers:
    base_yaw_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: shoulder_yaw
        joint_speed: 1.17
        motor:
            id: 1
            init: 512
            min: 0
            max: 1023

    torso_pitch_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller_dual_motor
            type: JointPositionControllerDual
        joint_name: shoulder_pitch
        joint_speed: 1.17
        motor_master:
            id: 2
            init: 512
            min: 215
            max: 815
        motor_slave:
            id: 3

    elbow_pitch_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller_dual_motor
            type: JointPositionControllerDual
        joint_name: elbow_pitch
        joint_speed: 1.17
        motor_master:
            id: 4
            init: 512
            min: 210
            max: 830
        motor_slave:
            id: 5

    wrist_pitch_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: wrist_pitch
        joint_speed: 1.17
        motor:
            id: 6
            init: 512
            min: 220
            max: 820

    wrist_yaw_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: wrist_roll
        joint_speed: 1.17
        motor:
            id: 7
            init: 512
            min: 0
            max: 1020

    # min and max angles swapped so valid angles are all positive
    gripper_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: gripper_joint
        joint_speed: 1.17
        motor:
            id: 8
            init: 512
            min: 512
            max: 20