jnt_controller:
    # controller: # single motor controller (WORKS)
    #     package: dynamixel_controllers
    #     module: joint_position_controller
    #     type: JointPositionController
    # joint_name: jnt
    # joint_speed: 1.17
    # motor:
    #     id: 1
    #     init: 512
    #     min: 0
    #     max: 1023

    controller: # dual motor controller (WORKS)
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: jnt
    joint_speed: 0.5
    motor_master:
        id: 4
        init: 512
        min: 215
        max: 815
    motor_slave:
        id: 5